checkpoint_path: "/home/asus-mivia/Desktop/Multi-Task-LFD/repo/osvi-wm/runs/ur5e_pick_place_balanced_20260820_165229/checkpoints/best.pt"
training_config_path: "/home/asus-mivia/Desktop/Multi-Task-LFD/repo/osvi-wm/runs/ur5e_pick_place_balanced_20260820_165229/config.yaml"
projection_matrix_path: "/home/asus-mivia/Desktop/Multi-Task-LFD/repo/osvi-wm/configs/ur5e_zed_front_projection.yaml"
device: "cuda"

image:
  front_camera_index: 0
  height: 240
  width: 320
  crop: [0, 0, 0, 0]
  normalize: true
  live_images_are_rgb: false
  demo_convert_bgr_to_rgb: false

context:
  num_frames: 10
  sample_sides: true
  deterministic: true

agent_observation:
  num_frames: 2
  repeat_current_image: true

waypoints:
  base_count: 5
  sub_waypoints: true
  predicted_count: 15
  selected_count: 5
  selection: "last_group"
  image_waypoints: true

projection:
  output_frame: "base_link"

control:
  action_format: "absolute_pose_quat_gripper"
  orientation_mode: "fixed_top_down"
  fixed_orientation_xyzw:
    - 0.9994452044624775
    - 0.03161651380119412
    - 0.0021438049655468088
    - 0.010251021036213035
  gripper_open_position: 0.0
  gripper_closed_position: 255.0
  gripper_close_threshold: 0.18
  max_actions_per_inference: 5

grasp_refinement:
  enabled: false

safety:
  clamp_workspace: false
  workspace_min: [-0.50, 0.20, 0.02]
  workspace_max: [0.50, 0.90, 0.50]
  min_waypoint_distance: 0.005

debug:
  show_waypoint_overlay: false
  save_waypoint_overlay: true
  waypoint_overlay_window: "OSVI waypoint overlay"
  waypoint_overlay_wait_ms: 1